name: dishdash

services:
  backend:
    build:
      context: .
    container_name: dishdash-django
    ports:
      - "8000:8000"
    env_file:
      - ./dishdash/.env
    volumes:
       - ./media:/media
       - ./static:/static
    depends_on:
      postgres:
        condition: service_healthy  
  postgres:
    image: postgres
    container_name: dishdash-container
    command: -p 5432
    ports:
      - "5432:5432"
    env_file:
      - ./dishdash/.env
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  


volumes:
  postgres_data: