# Generated by Django 5.0.8 on 2024-09-30 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('order_email', models.EmailField(max_length=200)),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True)),
                ('order_address', models.TextField(max_length=800)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('order_total', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=250)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Shipping', 'Shipping'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200)),
                ('tracking_number', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
    ]
