# Generated by Django 5.0.8 on 2024-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('POD', 'POD'), ('Paystack', 'Paystack')], max_length=250),
        ),
    ]
